# Generated by Django 2.1.5 on 2019-02-09 06:24

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190209_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={True}),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Product Status'),
        ),
    ]
