# Generated by Django 2.1.5 on 2019-02-09 06:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190209_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Product Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='available', when={True}),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='available'),
        ),
    ]
